// Auto-generated by setup-network.js
// This file is used for local network testing (PC + Tablet)
// It overrides environment.ts values

export const environment = {
  production: false,
  // GraphQL endpoints
  graphqlEndpoint: 'http://localhost:4000/graphql',
  graphqlWsEndpoint: 'ws://localhost:4000/graphql',
  // WebRTC Signaling Server (auto-detected local IP)
  signalingServerUrl: 'http://192.168.1.136:3001',
  // App server port
  appPort: 8100,
};
