const os = require('os');
const fs = require('fs');
const path = require('path');

/**
 * Auto-detect local IP address and create environment configuration
 */
function getLocalIpAddress() {
  const interfaces = os.networkInterfaces();

  for (const name of Object.keys(interfaces)) {
    for (const iface of interfaces[name]) {
      // Skip internal (loopback) and non-IPv4 addresses
      if (iface.family === 'IPv4' && !iface.internal) {
        return iface.address;
      }
    }
  }

  return 'localhost';
}

function createEnvironmentFile() {
  const localIp = getLocalIpAddress();
  const signalingPort = process.env.SIGNALING_PORT || 3001;
  const appPort = process.env.APP_PORT || 8100;

  console.log('\n🔍 Network Configuration Detected:');
  console.log('═══════════════════════════════════════');
  console.log(`📍 Local IP Address: ${localIp}`);
  console.log(`🔌 Signaling Server: http://${localIp}:${signalingPort}`);
  console.log(`📱 App Server: http://${localIp}:${appPort}`);
  console.log('═══════════════════════════════════════\n');

  // Create environment.local.ts (overrides environment.ts)
  const environmentContent = `// Auto-generated by setup-network.js
// This file is used for local network testing (PC + Tablet)
// It overrides environment.ts values

export const environment = {
  production: false,
  // GraphQL endpoints
  graphqlEndpoint: 'http://localhost:4000/graphql',
  graphqlWsEndpoint: 'ws://localhost:4000/graphql',
  // WebRTC Signaling Server (auto-detected local IP)
  signalingServerUrl: 'http://${localIp}:${signalingPort}',
  // App server port
  appPort: ${appPort},
};
`;

  const envPath = path.join(__dirname, '..', 'src', 'environments', 'environment.ts');

  // Backup original if it exists
  if (fs.existsSync(envPath)) {
    const backupPath = path.join(__dirname, '..', 'src', 'environments', 'environment.backup.ts');
    if (!fs.existsSync(backupPath)) {
      fs.copyFileSync(envPath, backupPath);
      console.log('✅ Backed up original environment.ts → environment.backup.ts');
    }
  }

  // Write new environment file
  fs.writeFileSync(envPath, environmentContent);
  console.log('✅ Updated environment.ts with local IP address\n');

  // Create .env file for signaling server
  const serverEnvPath = path.join(__dirname, '..', '..', 'webrtc-signaling-server', '.env');
  const serverEnvContent = `PORT=${signalingPort}
ALLOWED_ORIGINS=http://${localIp}:${appPort},http://localhost:${appPort}
NODE_ENV=development
`;

  fs.writeFileSync(serverEnvPath, serverEnvContent);
  console.log('✅ Created .env file for signaling server\n');

  // Display instructions
  console.log('📋 Next Steps:');
  console.log('═══════════════════════════════════════');
  console.log('1. Start signaling server:');
  console.log('   cd ..\\webrtc-signaling-server && npm run dev\n');
  console.log('2. Start Ionic app:');
  console.log('   npm run serve\n');
  console.log('3. On your tablet, open:');
  console.log(`   http://${localIp}:${appPort}/video-call\n`);
  console.log('4. On your PC, open:');
  console.log(`   http://localhost:${appPort}/video-call\n`);
  console.log('═══════════════════════════════════════\n');
}

// Run the setup
try {
  createEnvironmentFile();
} catch (error) {
  console.error('❌ Error setting up network configuration:', error);
  process.exit(1);
}
