// src/app/services/chapters/data/chapter-28.data.ts

import { Chapter } from '@app/models/chapter.model';

export const CHAPTER_28_DATA: Chapter = {
  id: 28,
  title: 'Social Media Advertising & PWA',
  description: 'Create social media advertising campaigns that drive users to a Progressive Web App with integrated media gallery, featuring Instagram, TikTok, Facebook, and YouTube ads integration, deep linking, multi-platform analytics, and conversion tracking.',
  icon: 'megaphone-outline',
  category: 'expert',
  completed: false,
  hasDemo: true,
  sections: [
    {
      id: 280,
      title: 'Progressive Web App Fundamentals',
      content: `
        <h2>Understanding Progressive Web Apps (PWAs)</h2>
        <p>A Progressive Web App is a web application that uses modern web capabilities to deliver an app-like experience. PWAs are installable, work offline, can send push notifications, and provide fast, reliable performance without app store downloads.</p>

        <h3>Key PWA Characteristics</h3>
        <ul>
          <li><strong>Progressive:</strong> Works for all users, regardless of browser choice</li>
          <li><strong>Responsive:</strong> Fits any form factor (desktop, mobile, tablet)</li>
          <li><strong>Connectivity Independent:</strong> Enhanced with service workers to work offline</li>
          <li><strong>App-like:</strong> Feels like an app with app-style interactions</li>
          <li><strong>Fresh:</strong> Always up-to-date via service worker update process</li>
          <li><strong>Safe:</strong> Served via HTTPS to prevent snooping</li>
          <li><strong>Discoverable:</strong> Identifiable as "application" via W3C manifest</li>
          <li><strong>Re-engageable:</strong> Push notifications for re-engagement</li>
          <li><strong>Installable:</strong> Add to home screen without app store</li>
          <li><strong>Linkable:</strong> Easily shared via URL</li>
        </ul>

        <h3>Service Worker Lifecycle</h3>
        <p>The service worker lifecycle consists of several stages:</p>
        <ol>
          <li><strong>Register:</strong> Browser downloads and parses service worker</li>
          <li><strong>Install:</strong> Service worker installed, cache static assets</li>
          <li><strong>Activate:</strong> Old service worker removed, new one takes control</li>
          <li><strong>Fetch:</strong> Intercept network requests, serve from cache</li>
          <li><strong>Update:</strong> Check for new service worker on navigation</li>
        </ol>

        <h3>Web App Manifest</h3>
        <p>The manifest.webmanifest file tells the browser how to behave when the PWA is installed:</p>
        <ul>
          <li>App name and short name</li>
          <li>Icons (multiple sizes for different devices)</li>
          <li>Start URL</li>
          <li>Display mode (standalone, fullscreen, minimal-ui)</li>
          <li>Theme and background colors</li>
          <li>Orientation preferences</li>
          <li>Screenshots for app stores</li>
          <li>App shortcuts</li>
        </ul>

        <h3>PWA vs Native Apps</h3>
        <table>
          <tr>
            <th>Feature</th>
            <th>PWA</th>
            <th>Native App</th>
          </tr>
          <tr>
            <td>Installation</td>
            <td>Direct from website</td>
            <td>App store required</td>
          </tr>
          <tr>
            <td>Updates</td>
            <td>Automatic, instant</td>
            <td>Manual download</td>
          </tr>
          <tr>
            <td>Size</td>
            <td>Smaller (MB)</td>
            <td>Larger (10-100+ MB)</td>
          </tr>
          <tr>
            <td>Development</td>
            <td>One codebase</td>
            <td>Separate iOS/Android</td>
          </tr>
          <tr>
            <td>SEO</td>
            <td>Fully indexed</td>
            <td>Not indexed</td>
          </tr>
          <tr>
            <td>Sharing</td>
            <td>Via URL</td>
            <td>Deep links only</td>
          </tr>
        </table>
      `,
      codeSnippets: [
        {
          id: 1,
          language: 'typescript',
          title: 'Service Worker with Workbox',
          code: `// src/service-worker.ts
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

declare const self: ServiceWorkerGlobalScope;

// Precache static assets (generated by Workbox)
precacheAndRoute(self.__WB_MANIFEST);

// Cache images with CacheFirst strategy
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
        purgeOnQuotaError: true,
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache API responses with NetworkFirst strategy
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 5 * 60, // 5 minutes
      }),
    ],
  })
);

// Install event
self.addEventListener('install', (event) => {
  console.log('[Service Worker] Installing...');
  self.skipWaiting();
});

// Activate event
self.addEventListener('activate', (event) => {
  console.log('[Service Worker] Activating...');
  event.waitUntil(self.clients.claim());
});`,
          copyable: true,
        },
        {
          id: 2,
          language: 'typescript',
          title: 'PWA Service - Installation & Updates',
          code: `// src/app/services/pwa/pwa.service.ts
import { Injectable } from '@angular/core';
import { SwUpdate, VersionReadyEvent } from '@angular/service-worker';
import { BehaviorSubject, Observable, filter } from 'rxjs';

export interface BeforeInstallPromptEvent extends Event {
  readonly platforms: string[];
  readonly userChoice: Promise<{
    outcome: 'accepted' | 'dismissed';
    platform: string;
  }>;
  prompt(): Promise<void>;
}

@Injectable({
  providedIn: 'root'
})
export class PwaService {
  private deferredPrompt: BeforeInstallPromptEvent | null = null;
  private installable$ = new BehaviorSubject<boolean>(false);
  private installed$ = new BehaviorSubject<boolean>(false);

  constructor(private readonly swUpdate: SwUpdate) {
    this.init();
  }

  private init(): void {
    this.checkIfInstalled();

    // Listen for beforeinstallprompt event
    window.addEventListener('beforeinstallprompt', (e: Event) => {
      e.preventDefault();
      this.deferredPrompt = e as BeforeInstallPromptEvent;
      this.installable$.next(true);
    });

    // Listen for app installed event
    window.addEventListener('appinstalled', () => {
      this.installed$.next(true);
      this.deferredPrompt = null;
      this.installable$.next(false);
    });

    // Check for service worker updates
    if (this.swUpdate.isEnabled) {
      this.swUpdate.versionUpdates
        .pipe(
          filter((evt): evt is VersionReadyEvent => evt.type === 'VERSION_READY')
        )
        .subscribe(() => {
          this.promptUserToUpdate();
        });
    }
  }

  private checkIfInstalled(): void {
    const isStandalone = window.matchMedia('(display-mode: standalone)').matches;
    const isIosStandalone = (window.navigator as any).standalone === true;
    this.installed$.next(isStandalone || isIosStandalone);
  }

  isInstallable(): Observable<boolean> {
    return this.installable$.asObservable();
  }

  async promptInstall(): Promise<boolean> {
    if (!this.deferredPrompt) return false;

    try {
      await this.deferredPrompt.prompt();
      const { outcome } = await this.deferredPrompt.userChoice;
      this.deferredPrompt = null;
      this.installable$.next(false);
      return outcome === 'accepted';
    } catch (error) {
      console.error('Error prompting PWA install:', error);
      return false;
    }
  }

  private async promptUserToUpdate(): Promise<void> {
    const updateConfirmed = confirm('New version available. Update now?');
    if (updateConfirmed) {
      await this.swUpdate.activateUpdate();
      document.location.reload();
    }
  }
}`,
          copyable: true,
        },
      ],
      interviewTips: [
        'PWA benefits: No app store, instant updates, smaller size, cross-platform with one codebase, SEO-friendly, shareable via URL',
        'Service worker lifecycle: Register → Install (cache assets) → Activate (claim clients) → Fetch (intercept requests) → Update',
        'Workbox strategies: CacheFirst (offline-first for static), NetworkFirst (fresh content priority for API), StaleWhileRevalidate (fast + fresh)',
        'Installation: beforeinstallprompt event captured, deferred, triggered on user action; standalone mode detection',
        'Manifest: Defines app metadata (name, icons, start URL, display mode, theme color) for installation',
      ],
    },
    {
      id: 281,
      title: 'Social Media Advertising Platforms',
      content: `
        <h2>Major Advertising Platforms</h2>
        <p>Each social media platform has unique strengths, audiences, and ad formats. Understanding these differences is critical for effective campaign planning.</p>

        <h3>Platform Comparison</h3>
        <table>
          <tr>
            <th>Platform</th>
            <th>Strengths</th>
            <th>Demographics</th>
            <th>Average CPC</th>
          </tr>
          <tr>
            <td>Instagram</td>
            <td>Visual storytelling, high engagement</td>
            <td>18-34, 50% female</td>
            <td>$0.50 - $2.00</td>
          </tr>
          <tr>
            <td>TikTok</td>
            <td>Viral potential, creative freedom</td>
            <td>16-24 (Gen Z)</td>
            <td>$0.10 - $0.30</td>
          </tr>
          <tr>
            <td>Facebook</td>
            <td>Massive reach, advanced targeting</td>
            <td>25-54, diverse</td>
            <td>$0.50 - $2.00</td>
          </tr>
          <tr>
            <td>YouTube</td>
            <td>Video platform, search intent</td>
            <td>All ages, slight male skew</td>
            <td>$0.10 - $0.30</td>
          </tr>
        </table>

        <h3>Campaign Structure (All Platforms)</h3>
        <p>All platforms use a 3-tier hierarchy:</p>
        <ol>
          <li><strong>Campaign:</strong> Objective (traffic, conversions, engagement), overall budget</li>
          <li><strong>Ad Set/Group:</strong> Targeting (location, age, interests), placement, budget</li>
          <li><strong>Ad:</strong> Creative (image/video, copy), CTA, destination URL</li>
        </ol>

        <h3>Ad Creative Best Practices</h3>
        <table>
          <tr>
            <th>Element</th>
            <th>Best Practice</th>
          </tr>
          <tr>
            <td>Video Length</td>
            <td>15-30s (TikTok: 21-34s optimal)</td>
          </tr>
          <tr>
            <td>Hook</td>
            <td>First 3 seconds crucial</td>
          </tr>
          <tr>
            <td>Sound</td>
            <td>Design for sound-off (85% watch muted)</td>
          </tr>
          <tr>
            <td>Captions</td>
            <td>Always include text overlays</td>
          </tr>
          <tr>
            <td>CTA</td>
            <td>Clear, action-oriented, visible</td>
          </tr>
          <tr>
            <td>Branding</td>
            <td>Subtle, native to platform</td>
          </tr>
        </table>
      `,
      codeSnippets: [
        {
          id: 3,
          language: 'typescript',
          title: 'Campaign Objectives & Metrics',
          code: `// Campaign objective types across platforms
export type CampaignObjective =
  | 'awareness'          // Brand awareness, reach
  | 'traffic'            // Website clicks, landing page views
  | 'engagement'         // Likes, comments, shares
  | 'leads'              // Form submissions, sign-ups
  | 'app_installs'       // App/PWA downloads
  | 'sales'              // Conversions, purchases
  | 'video_views';       // Video watch time

// Key performance metrics
interface AdPerformanceMetrics {
  awareness: {
    impressions: number;          // Total ad views
    reach: number;                // Unique users
    frequency: number;            // Impressions / Reach
    cpm: number;                  // Cost per 1,000 impressions
  };

  engagement: {
    clicks: number;               // Total clicks
    ctr: number;                  // Click-through rate (%)
    engagementRate: number;       // (Likes + Comments + Shares) / Reach
    videoCompletionRate: number;  // % who watched to end
  };

  conversion: {
    conversions: number;          // Total conversions
    cpc: number;                  // Cost per click
    cpa: number;                  // Cost per acquisition
    conversionRate: number;       // Conversions / Clicks (%)
    roas: number;                 // Return on ad spend
  };
}

// Targeting configuration
interface AdTargeting {
  demographics: {
    ageMin: number;
    ageMax: number;
    genders: ('male' | 'female' | 'all')[];
    languages: string[];
  };

  location: {
    countries: string[];
    regions: string[];
    cities: string[];
  };

  interests: {
    categories: string[];    // Interest category IDs
    behaviors: string[];     // Behavior IDs
    keywords: string[];      // Keyword targeting
  };

  placements: {
    devices: ('mobile' | 'desktop' | 'tablet')[];
    positions: ('feed' | 'stories' | 'reels' | 'explore')[];
  };
}`,
          copyable: true,
        },
      ],
      interviewTips: [
        'Platform selection: Instagram for visual brands, TikTok for Gen Z viral, Facebook for broad reach, YouTube for video content',
        'Campaign hierarchy: Campaign (objective, budget) → Ad Set (targeting, placement) → Ad (creative, CTA)',
        'Creative: Hook in 3 seconds, design for sound-off, use captions, match platform style, clear CTA',
        'Metrics: CTR (clicks/impressions), CPA (spend/conversions), ROAS (revenue/spend), engagement rate',
        'Targeting: Start broad, narrow based on data; use lookalike audiences for scale; exclude converters if prospecting',
      ],
    },
    {
      id: 282,
      title: 'Instagram Ads Integration (Meta Graph API)',
      content: `
        <h2>Instagram Advertising via Meta Graph API</h2>
        <p>Instagram ads use Facebook's Meta Graph API. Same API structure, different placements (Instagram Feed, Stories, Reels, Explore).</p>

        <h3>API Structure</h3>
        <p>Endpoint: <code>https://graph.facebook.com/v18.0</code></p>
        <p>Authentication: OAuth 2.0 access token</p>
        <p>Account ID: <code>act_ACCOUNT_ID</code></p>

        <h3>Campaign Creation Flow</h3>
        <ol>
          <li>Create campaign (objective, budget)</li>
          <li>Upload creative (image or video)</li>
          <li>Create ad set (targeting, placement, budget)</li>
          <li>Create ad (creative, copy, CTA, destination URL)</li>
          <li>Activate campaign</li>
        </ol>

        <h3>Instagram Placements</h3>
        <ul>
          <li><strong>Feed:</strong> Main scrolling feed (4:5 or 1:1 aspect ratio)</li>
          <li><strong>Stories:</strong> Full-screen vertical (9:16 aspect ratio, 15s max)</li>
          <li><strong>Reels:</strong> Full-screen vertical (9:16 aspect ratio, 15-90s)</li>
          <li><strong>Explore:</strong> Discover page grid</li>
        </ul>

        <h3>Creative Specifications</h3>
        <table>
          <tr>
            <th>Placement</th>
            <th>Aspect Ratio</th>
            <th>Resolution</th>
            <th>Length</th>
          </tr>
          <tr>
            <td>Feed</td>
            <td>4:5 or 1:1</td>
            <td>1080x1080 min</td>
            <td>15-60s</td>
          </tr>
          <tr>
            <td>Stories</td>
            <td>9:16</td>
            <td>1080x1920</td>
            <td>15s max</td>
          </tr>
          <tr>
            <td>Reels</td>
            <td>9:16</td>
            <td>1080x1920</td>
            <td>15-90s</td>
          </tr>
        </table>
      `,
      codeSnippets: [
        {
          id: 4,
          language: 'typescript',
          title: 'Instagram Ads Service - Complete Implementation',
          code: `// src/app/services/ads/instagram-ads.service.ts
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

export interface InstagramAdConfig {
  accountId: string;
  accessToken: string;
  adName: string;
  targeting: InstagramTargeting;
  creative: InstagramCreative;
  budget: AdBudget;
}

export interface InstagramTargeting {
  geoLocations: {
    countries?: string[];
    cities?: Array<{ key: string; name: string }>;
  };
  ageMin: number;
  ageMax: number;
  genders: number[]; // 1=male, 2=female
  interests: Array<{ id: string; name: string }>;
  instagramPositions?: ('stream' | 'story' | 'explore' | 'reels')[];
}

export interface InstagramCreative {
  imageHash?: string;
  videoId?: string;
  caption: string;
  callToAction: 'LEARN_MORE' | 'SHOP_NOW' | 'SIGN_UP' | 'DOWNLOAD';
  destinationUrl: string;
  instagramAccountId: string;
}

export interface AdBudget {
  dailyBudget?: number; // In cents
  lifetimeBudget?: number;
  bidStrategy: 'LOWEST_COST_WITHOUT_CAP' | 'LOWEST_COST_WITH_BID_CAP';
}

@Injectable({
  providedIn: 'root'
})
export class InstagramAdsService {
  private readonly apiUrl = 'https://graph.facebook.com/v18.0';

  constructor(private readonly http: HttpClient) {}

  createCampaign(config: {
    accountId: string;
    accessToken: string;
    name: string;
    objective: 'OUTCOME_TRAFFIC' | 'OUTCOME_ENGAGEMENT';
  }): Observable<{ id: string }> {
    const endpoint = \`\${this.apiUrl}/act_\${config.accountId}/campaigns\`;

    return this.http.post<any>(endpoint, null, {
      params: {
        name: config.name,
        objective: config.objective,
        status: 'PAUSED',
        access_token: config.accessToken
      }
    }).pipe(
      map(response => ({ id: response.id }))
    );
  }

  createAdSet(config: {
    accountId: string;
    accessToken: string;
    campaignId: string;
    name: string;
    targeting: InstagramTargeting;
    budget: AdBudget;
  }): Observable<{ id: string }> {
    const endpoint = \`\${this.apiUrl}/act_\${config.accountId}/adsets\`;

    const targeting = {
      geo_locations: config.targeting.geoLocations,
      age_min: config.targeting.ageMin,
      age_max: config.targeting.ageMax,
      genders: config.targeting.genders,
      interests: config.targeting.interests,
      publisher_platforms: ['instagram'],
      instagram_positions: config.targeting.instagramPositions || ['stream']
    };

    return this.http.post<any>(endpoint, null, {
      params: {
        name: config.name,
        campaign_id: config.campaignId,
        targeting: JSON.stringify(targeting),
        daily_budget: config.budget.dailyBudget,
        bid_strategy: config.budget.bidStrategy,
        status: 'PAUSED',
        access_token: config.accessToken
      }
    }).pipe(
      map(response => ({ id: response.id }))
    );
  }

  createAd(config: {
    accountId: string;
    accessToken: string;
    adSetId: string;
    name: string;
    creative: InstagramCreative;
  }): Observable<{ id: string }> {
    const endpoint = \`\${this.apiUrl}/act_\${config.accountId}/ads\`;

    const objectStorySpec = {
      instagram_actor_id: config.creative.instagramAccountId,
      link_data: {
        call_to_action: {
          type: config.creative.callToAction,
          value: { link: config.creative.destinationUrl }
        },
        link: config.creative.destinationUrl,
        message: config.creative.caption,
        image_hash: config.creative.imageHash
      }
    };

    return this.http.post<any>(endpoint, null, {
      params: {
        name: config.name,
        adset_id: config.adSetId,
        creative: JSON.stringify({ object_story_spec: objectStorySpec }),
        status: 'PAUSED',
        access_token: config.accessToken
      }
    }).pipe(
      map(response => ({ id: response.id }))
    );
  }

  getAdInsights(adId: string, accessToken: string): Observable<any> {
    const endpoint = \`\${this.apiUrl}/\${adId}/insights\`;
    const fields = 'impressions,clicks,spend,ctr,cpc,reach,frequency';

    return this.http.get<any>(endpoint, {
      params: {
        fields,
        access_token: accessToken
      }
    });
  }
}`,
          copyable: true,
        },
      ],
      interviewTips: [
        'Meta Graph API: Same API for Instagram and Facebook, different publisher_platforms and positions',
        'Hierarchy: Campaign → Ad Set → Ad; campaign has objective, ad set has targeting/budget, ad has creative',
        'Creative upload: Images/videos must be uploaded first to get hash/ID, then referenced in ad creation',
        'Targeting: geoLocations (countries/cities), age range, genders, interests; instagram_positions for placement',
        'Insights: Use /insights endpoint with fields parameter to get metrics (impressions, clicks, spend, CTR, CPC)',
      ],
    },
    {
      id: 283,
      title: 'TikTok & YouTube Ads Integration',
      content: `
        <h2>TikTok Business API</h2>
        <p>TikTok uses a different API structure than Meta. Key differences: Ad Group instead of Ad Set, age groups (not ranges), video-first platform.</p>

        <h3>TikTok API Structure</h3>
        <p>Endpoint: <code>https://business-api.tiktok.com/open_api/v1.3</code></p>
        <p>Authentication: Access-Token header</p>
        <p>Hierarchy: Campaign → Ad Group → Ad</p>

        <h3>TikTok Targeting Differences</h3>
        <ul>
          <li>Age groups (AGE_18_24) not ranges (18-24)</li>
          <li>Device price ranges (PRICE_0_199, PRICE_500_999)</li>
          <li>Operating systems (ANDROID, IOS)</li>
          <li>Network types (4G, 5G, WIFI)</li>
        </ul>

        <h2>YouTube Ads (Google Ads API)</h2>
        <p>YouTube uses Google Ads API with video-specific features.</p>

        <h3>YouTube API Structure</h3>
        <p>Endpoint: <code>https://googleads.googleapis.com/v14</code></p>
        <p>Authentication: OAuth 2.0 Bearer token + developer-token header</p>
        <p>Hierarchy: Customer → Campaign → Ad Group → Ad</p>

        <h3>YouTube Ad Formats</h3>
        <ul>
          <li><strong>Skippable In-Stream:</strong> 15-30s, skip after 5s</li>
          <li><strong>Non-Skippable:</strong> 15s, must watch</li>
          <li><strong>Bumper:</strong> 6s, non-skippable</li>
          <li><strong>Shorts:</strong> 15-60s vertical video</li>
        </ul>
      `,
      codeSnippets: [
        {
          id: 5,
          language: 'typescript',
          title: 'TikTok Ads Service',
          code: `// src/app/services/ads/tiktok-ads.service.ts
import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

export type TikTokAgeGroup = 'AGE_18_24' | 'AGE_25_34' | 'AGE_35_44' | 'AGE_45_54';
export type TikTokGender = 'MALE' | 'FEMALE' | 'UNLIMITED';

export interface TikTokTargeting {
  locations: string[];
  ageGroups: TikTokAgeGroup[];
  genders: TikTokGender[];
  languages: string[];
  interests?: string[];
  operatingSystems?: ('ANDROID' | 'IOS')[];
}

@Injectable({
  providedIn: 'root'
})
export class TikTokAdsService {
  private readonly apiUrl = 'https://business-api.tiktok.com/open_api/v1.3';

  constructor(private readonly http: HttpClient) {}

  private getHeaders(accessToken: string): HttpHeaders {
    return new HttpHeaders({
      'Access-Token': accessToken,
      'Content-Type': 'application/json'
    });
  }

  createCampaign(config: {
    advertiserId: string;
    accessToken: string;
    campaignName: string;
    objective: 'TRAFFIC' | 'CONVERSIONS' | 'VIDEO_VIEWS';
  }): Observable<{ campaignId: string }> {
    const endpoint = \`\${this.apiUrl}/campaign/create/\`;

    return this.http.post<any>(
      endpoint,
      {
        advertiser_id: config.advertiserId,
        campaign_name: config.campaignName,
        objective_type: config.objective,
        budget_mode: 'BUDGET_MODE_INFINITE'
      },
      { headers: this.getHeaders(config.accessToken) }
    ).pipe(
      map(response => ({ campaignId: response.data.campaign_id }))
    );
  }

  createAdGroup(config: {
    advertiserId: string;
    accessToken: string;
    campaignId: string;
    adGroupName: string;
    targeting: TikTokTargeting;
    budget: number; // In cents
  }): Observable<{ adGroupId: string }> {
    const endpoint = \`\${this.apiUrl}/adgroup/create/\`;

    return this.http.post<any>(
      endpoint,
      {
        advertiser_id: config.advertiserId,
        campaign_id: config.campaignId,
        adgroup_name: config.adGroupName,
        location_ids: config.targeting.locations,
        age_groups: config.targeting.ageGroups,
        gender: config.targeting.genders,
        languages: config.targeting.languages,
        budget_mode: 'BUDGET_MODE_DAY',
        budget: config.budget,
        bid_type: 'BID_TYPE_NO_BID',
        optimization_goal: 'CLICK'
      },
      { headers: this.getHeaders(config.accessToken) }
    ).pipe(
      map(response => ({ adGroupId: response.data.adgroup_id }))
    );
  }

  createAd(config: {
    advertiserId: string;
    accessToken: string;
    adGroupId: string;
    videoId: string;
    adText: string;
    landingPageUrl: string;
  }): Observable<{ adId: string }> {
    const endpoint = \`\${this.apiUrl}/ad/create/\`;

    return this.http.post<any>(
      endpoint,
      {
        advertiser_id: config.advertiserId,
        adgroup_id: config.adGroupId,
        creatives: [{
          ad_text: config.adText,
          call_to_action: 'LEARN_MORE',
          landing_page_url: config.landingPageUrl,
          video_id: config.videoId
        }]
      },
      { headers: this.getHeaders(config.accessToken) }
    ).pipe(
      map(response => ({ adId: response.data.ad_ids[0] }))
    );
  }
}`,
          copyable: true,
        },
        {
          id: 6,
          language: 'typescript',
          title: 'YouTube Ads Service',
          code: `// src/app/services/ads/youtube-ads.service.ts
import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';

export interface YouTubeCreative {
  videoId: string;
  headline: string;
  description: string;
  callToAction: string;
  finalUrl: string;
}

@Injectable({
  providedIn: 'root'
})
export class YouTubeAdsService {
  private readonly apiUrl = 'https://googleads.googleapis.com/v14';

  constructor(private readonly http: HttpClient) {}

  private getHeaders(accessToken: string, customerId: string): HttpHeaders {
    return new HttpHeaders({
      'Authorization': \`Bearer \${accessToken}\`,
      'developer-token': 'YOUR_DEVELOPER_TOKEN',
      'login-customer-id': customerId,
      'Content-Type': 'application/json'
    });
  }

  createCampaign(config: {
    customerId: string;
    accessToken: string;
    campaignName: string;
    budgetMicros: number; // Amount in micros (1/1,000,000)
  }): Observable<{ campaignId: string }> {
    const endpoint = \`\${this.apiUrl}/customers/\${config.customerId}/campaigns:mutate\`;

    return this.http.post<any>(
      endpoint,
      {
        operations: [{
          create: {
            name: config.campaignName,
            advertising_channel_type: 'VIDEO',
            advertising_channel_sub_type: 'VIDEO_ACTION',
            status: 'PAUSED',
            bidding_strategy_type: 'MAXIMIZE_CONVERSIONS'
          }
        }]
      },
      { headers: this.getHeaders(config.accessToken, config.customerId) }
    ).pipe(
      map(response => ({
        campaignId: response.results[0].resourceName.split('/').pop()
      }))
    );
  }

  createVideoAd(config: {
    customerId: string;
    accessToken: string;
    adGroupId: string;
    creative: YouTubeCreative;
  }): Observable<{ adId: string }> {
    const endpoint = \`\${this.apiUrl}/customers/\${config.customerId}/adGroupAds:mutate\`;

    return this.http.post<any>(
      endpoint,
      {
        operations: [{
          create: {
            ad_group: \`customers/\${config.customerId}/adGroups/\${config.adGroupId}\`,
            status: 'ENABLED',
            ad: {
              video_ad: {
                video: {
                  asset: \`https://www.youtube.com/watch?v=\${config.creative.videoId}\`
                },
                in_stream: {
                  action_button_label: config.creative.callToAction,
                  action_headline: config.creative.headline
                }
              },
              final_urls: [config.creative.finalUrl]
            }
          }
        }]
      },
      { headers: this.getHeaders(config.accessToken, config.customerId) }
    ).pipe(
      map(response => ({
        adId: response.results[0].resourceName.split('/').pop()
      }))
    );
  }
}`,
          copyable: true,
        },
      ],
      interviewTips: [
        'TikTok differences: Ad Group not Ad Set, age groups not ranges, Access-Token header not params, video-first platform',
        'TikTok targeting: Device price ranges, operating systems, network types unique to TikTok',
        'YouTube API: Google Ads API, different auth (Bearer + developer-token), Customer→Campaign→AdGroup→Ad hierarchy',
        'YouTube video ads: Must upload video to YouTube first, use video ID in creative, in-stream format for skippable ads',
        'Platform-specific: Each platform has unique response structure, error handling, rate limits, and pagination',
      ],
    },
    {
      id: 284,
      title: 'Deep Linking & URL Parameters',
      content: `
        <h2>Deep Linking from Ads to PWA</h2>
        <p>Deep linking allows ads to direct users to specific content within your PWA, improving user experience and conversion rates.</p>

        <h3>UTM Parameters (Standard)</h3>
        <p>Universal tracking parameters for campaign attribution:</p>
        <ul>
          <li><strong>utm_source:</strong> Traffic source (instagram, tiktok, facebook, youtube)</li>
          <li><strong>utm_medium:</strong> Marketing medium (cpc, video, story, reel)</li>
          <li><strong>utm_campaign:</strong> Campaign name</li>
          <li><strong>utm_content:</strong> Ad variant (for A/B testing)</li>
          <li><strong>utm_term:</strong> Keywords (for paid search)</li>
        </ul>

        <h3>Custom Parameters</h3>
        <p>App-specific parameters for behavior control:</p>
        <ul>
          <li><strong>media_id:</strong> Specific media item to open</li>
          <li><strong>autoplay:</strong> Auto-play video on load</li>
          <li><strong>ad_id:</strong> Platform-specific ad identifier</li>
          <li><strong>variant:</strong> A/B test variant identifier</li>
        </ul>

        <h3>Example URL</h3>
        <pre><code>https://yourpwa.com/gallery?
utm_source=instagram&
utm_medium=story&
utm_campaign=summer2024&
utm_content=creative_a&
media_id=sunset_beach&
autoplay=true</code></pre>

        <h3>Attribution Models</h3>
        <table>
          <tr>
            <th>Model</th>
            <th>Description</th>
            <th>Use Case</th>
          </tr>
          <tr>
            <td>Last-Click</td>
            <td>100% credit to last touchpoint</td>
            <td>Simple, direct conversions</td>
          </tr>
          <tr>
            <td>First-Click</td>
            <td>100% credit to first touchpoint</td>
            <td>Brand awareness campaigns</td>
          </tr>
          <tr>
            <td>Linear</td>
            <td>Equal credit to all touchpoints</td>
            <td>Complex, multi-step journeys</td>
          </tr>
          <tr>
            <td>Time-Decay</td>
            <td>More credit to recent touchpoints</td>
            <td>Long sales cycles</td>
          </tr>
        </table>
      `,
      codeSnippets: [
        {
          id: 7,
          language: 'typescript',
          title: 'Deep Link Service - Complete Implementation',
          code: `// src/app/services/deep-linking/deep-link.service.ts
import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { AnalyticsService } from '@app/services/analytics/analytics.service';

export interface DeepLinkParams {
  // UTM Parameters
  source?: string;        // utm_source
  medium?: string;        // utm_medium
  campaign?: string;      // utm_campaign
  content?: string;       // utm_content
  term?: string;          // utm_term

  // Custom Parameters
  adId?: string;          // ad_id
  mediaId?: string;       // media_id
  autoPlay?: boolean;     // autoplay
  referrer?: string;      // ref
  variant?: string;       // A/B test variant
}

export interface CampaignData extends DeepLinkParams {
  timestamp: string;
  landingUrl: string;
  userAgent: string;
  sessionId?: string;
}

@Injectable({
  providedIn: 'root'
})
export class DeepLinkService {
  private readonly CAMPAIGN_STORAGE_KEY = 'campaign_data';
  private readonly SESSION_STORAGE_KEY = 'session_id';

  constructor(
    private readonly router: Router,
    private readonly analytics: AnalyticsService
  ) {}

  parseUrlParameters(): DeepLinkParams {
    const params = new URLSearchParams(window.location.search);

    return {
      // UTM parameters
      source: params.get('utm_source') || undefined,
      medium: params.get('utm_medium') || undefined,
      campaign: params.get('utm_campaign') || undefined,
      content: params.get('utm_content') || undefined,
      term: params.get('utm_term') || undefined,

      // Custom parameters
      adId: params.get('ad_id') || undefined,
      mediaId: params.get('media_id') || undefined,
      autoPlay: params.get('autoplay') === 'true',
      referrer: params.get('ref') || document.referrer,
      variant: params.get('variant') || undefined
    };
  }

  handleDeepLink(): void {
    const params = this.parseUrlParameters();

    // Track ad click if campaign parameters present
    if (params.source && params.campaign) {
      this.analytics.trackAdClick({
        source: params.source,
        medium: params.medium || 'unknown',
        campaign: params.campaign,
        content: params.content,
        adId: params.adId
      });
    }

    // Store campaign data for attribution
    this.storeCampaignData(params);

    // Navigate based on parameters
    this.navigateFromDeepLink(params);
  }

  private navigateFromDeepLink(params: DeepLinkParams): void {
    if (params.mediaId) {
      // Navigate to specific media item
      this.router.navigate(['/gallery', params.mediaId], {
        queryParams: {
          autoplay: params.autoPlay,
          source: params.source
        }
      });
    } else if (params.source) {
      // Navigate to gallery with source tracking
      this.router.navigate(['/gallery'], {
        queryParams: {
          source: params.source,
          campaign: params.campaign
        }
      });
    }
  }

  private storeCampaignData(params: DeepLinkParams): void {
    const campaignData: CampaignData = {
      ...params,
      timestamp: new Date().toISOString(),
      landingUrl: window.location.href,
      userAgent: navigator.userAgent,
      sessionId: this.getOrCreateSessionId()
    };

    sessionStorage.setItem(this.CAMPAIGN_STORAGE_KEY, JSON.stringify(campaignData));
  }

  getCampaignData(): CampaignData | null {
    const data = sessionStorage.getItem(this.CAMPAIGN_STORAGE_KEY);
    return data ? JSON.parse(data) : null;
  }

  private getOrCreateSessionId(): string {
    let sessionId = sessionStorage.getItem(this.SESSION_STORAGE_KEY);

    if (!sessionId) {
      sessionId = \`\${Date.now()}-\${Math.random().toString(36).substr(2, 9)}\`;
      sessionStorage.setItem(this.SESSION_STORAGE_KEY, sessionId);
    }

    return sessionId;
  }

  buildUrlWithUtm(baseUrl: string, params: DeepLinkParams): string {
    const url = new URL(baseUrl);

    if (params.source) url.searchParams.set('utm_source', params.source);
    if (params.medium) url.searchParams.set('utm_medium', params.medium);
    if (params.campaign) url.searchParams.set('utm_campaign', params.campaign);
    if (params.content) url.searchParams.set('utm_content', params.content);
    if (params.term) url.searchParams.set('utm_term', params.term);
    if (params.adId) url.searchParams.set('ad_id', params.adId);
    if (params.mediaId) url.searchParams.set('media_id', params.mediaId);
    if (params.autoPlay) url.searchParams.set('autoplay', 'true');

    return url.toString();
  }
}`,
          copyable: true,
        },
      ],
      interviewTips: [
        'UTM parameters: Standard for tracking (utm_source, utm_medium, utm_campaign, utm_content, utm_term)',
        'Custom parameters: App-specific behavior (media_id for content, autoplay for videos, ad_id for tracking)',
        'URL parsing: Use URLSearchParams API to extract parameters, store in sessionStorage for attribution',
        'Deep link routing: Navigate to specific content based on parameters, pass through for analytics',
        'Attribution: Last-click (simple), first-click (awareness), linear (equal credit), time-decay (recent weight)',
      ],
    },
    {
      id: 285,
      title: 'Landing Page with Media Gallery Widget',
      content: `
        <h2>Ad Landing Page Integration</h2>
        <p>The landing page is where users arrive after clicking your ad. It must be optimized for speed, mobile devices, and conversions.</p>

        <h3>Landing Page Optimization Principles</h3>
        <ul>
          <li><strong>Speed:</strong> Load time < 3 seconds (critical for ad traffic)</li>
          <li><strong>Mobile-First:</strong> 70%+ traffic from mobile devices</li>
          <li><strong>Message Match:</strong> Match ad promise (headline, imagery, offer)</li>
          <li><strong>Clear Value Prop:</strong> Above-the-fold, immediately visible</li>
          <li><strong>Minimal Friction:</strong> Few steps to desired action</li>
          <li><strong>Strong CTA:</strong> Clear, action-oriented, prominent</li>
        </ul>

        <h3>Core Web Vitals (Google)</h3>
        <table>
          <tr>
            <th>Metric</th>
            <th>What It Measures</th>
            <th>Target</th>
          </tr>
          <tr>
            <td>LCP</td>
            <td>Largest Contentful Paint (loading)</td>
            <td>< 2.5 seconds</td>
          </tr>
          <tr>
            <td>FID</td>
            <td>First Input Delay (interactivity)</td>
            <td>< 100 ms</td>
          </tr>
          <tr>
            <td>CLS</td>
            <td>Cumulative Layout Shift (visual stability)</td>
            <td>< 0.1</td>
          </tr>
        </table>

        <h3>Chapter 27 Widget Integration</h3>
        <p>Integrate the Interactive Media Gallery Widget from Chapter 27 to provide an engaging experience similar to Instagram Reels or TikTok.</p>

        <h3>Conversion Events to Track</h3>
        <ul>
          <li><strong>Like:</strong> Low-value engagement (value: 1)</li>
          <li><strong>Comment:</strong> Medium-value engagement (value: 5)</li>
          <li><strong>Save:</strong> High-value engagement (value: 10)</li>
          <li><strong>Video View:</strong> Watched > 10 seconds (value: 3)</li>
          <li><strong>PWA Install:</strong> Highest value (value: 50)</li>
        </ul>
      `,
      codeSnippets: [
        {
          id: 8,
          language: 'typescript',
          title: 'Ad Landing Page Component',
          code: `// src/app/pages/ad-landing/ad-landing.page.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IonicModule } from '@ionic/angular';
import { InteractiveMediaWidgetComponent } from '@app/lib/interactive-media-widget';
import { MediaObject, MediaInteractionEvent } from '@app/lib/interactive-media-widget/models';
import { DeepLinkService } from '@app/services/deep-linking/deep-link.service';
import { AnalyticsService } from '@app/services/analytics/analytics.service';
import { PwaService } from '@app/services/pwa/pwa.service';
import { Subject, takeUntil } from 'rxjs';

@Component({
  selector: 'app-ad-landing',
  templateUrl: './ad-landing.page.html',
  styleUrls: ['./ad-landing.page.scss'],
  standalone: true,
  imports: [CommonModule, IonicModule, InteractiveMediaWidgetComponent]
})
export class AdLandingPage implements OnInit, OnDestroy {
  mediaItems: MediaObject[] = [];
  widgetConfig = {
    enableGestures: true,
    enableActionBar: true,
    enableViewTracking: true,
    autoPlayVideos: false,
    showOverlays: true,
    theme: 'dark'
  };

  showInstallPrompt = false;
  campaignSource = '';
  private destroy$ = new Subject<void>();

  constructor(
    private readonly deepLinkService: DeepLinkService,
    private readonly analytics: AnalyticsService,
    private readonly pwaService: PwaService
  ) {}

  ngOnInit() {
    // Handle deep link parameters
    this.deepLinkService.handleDeepLink();

    // Get campaign data
    const campaignData = this.deepLinkService.getCampaignData();
    this.campaignSource = campaignData?.source || '';

    // Load media items
    this.loadMediaItems(campaignData?.mediaId);

    // Check if autoplay requested
    if (campaignData?.autoPlay) {
      this.widgetConfig = { ...this.widgetConfig, autoPlayVideos: true };
    }

    // Check PWA install availability
    this.pwaService.isInstallable()
      .pipe(takeUntil(this.destroy$))
      .subscribe(installable => {
        this.showInstallPrompt = installable;
      });

    // Track page view
    this.analytics.trackPageView('ad_landing', {
      source: campaignData?.source,
      campaign: campaignData?.campaign
    });
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  private loadMediaItems(startMediaId?: string): void {
    // Load from API or static data
    this.mediaItems = [
      {
        id: 'sunset_beach',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e',
        metadata: { title: 'Sunset Beach', likes: 1250 }
      },
      // ... more items
    ];

    // Prioritize specific media if requested
    if (startMediaId) {
      const index = this.mediaItems.findIndex(item => item.id === startMediaId);
      if (index > 0) {
        const item = this.mediaItems[index];
        this.mediaItems.splice(index, 1);
        this.mediaItems.unshift(item);
      }
    }
  }

  onMediaInteraction(event: MediaInteractionEvent): void {
    this.analytics.trackMediaInteraction(event);

    switch (event.eventType) {
      case 'like':
        this.analytics.trackConversion('like', {
          mediaId: event.mediaId,
          value: 1
        });
        break;
      case 'comment':
        this.analytics.trackConversion('comment', {
          mediaId: event.mediaId,
          value: 5
        });
        break;
      case 'save':
        this.analytics.trackConversion('save', {
          mediaId: event.mediaId,
          value: 10
        });
        break;
    }
  }

  async installPwa(): Promise<void> {
    const installed = await this.pwaService.promptInstall();

    if (installed) {
      this.analytics.trackConversion('pwa_installed', {
        value: 50,
        metadata: { source: this.campaignSource }
      });
      this.showInstallPrompt = false;
    }
  }
}`,
          copyable: true,
        },
        {
          id: 9,
          language: 'html',
          title: 'Landing Page Template',
          code: `<!-- src/app/pages/ad-landing/ad-landing.page.html -->
<ion-content [fullscreen]="true" class="ad-landing-content">
  <!-- PWA Install Prompt -->
  <div class="pwa-install-prompt" *ngIf="showInstallPrompt">
    <div class="prompt-content">
      <ion-icon name="download-outline"></ion-icon>
      <div class="prompt-text">
        <h3>Install App</h3>
        <p>Get the full experience!</p>
      </div>
      <ion-button (click)="installPwa()" size="small" color="primary">
        Install
      </ion-button>
      <ion-button (click)="showInstallPrompt = false" size="small" fill="clear">
        <ion-icon name="close" slot="icon-only"></ion-icon>
      </ion-button>
    </div>
  </div>

  <!-- Media Gallery Widget (Chapter 27) -->
  <app-interactive-media-widget
    [mediaList]="mediaItems"
    [config]="widgetConfig"
    (onInteraction)="onMediaInteraction($event)"
  ></app-interactive-media-widget>
</ion-content>`,
          copyable: true,
        },
      ],
      interviewTips: [
        'Landing page optimization: < 3s load time, mobile-first design, match ad promise, clear value prop above fold',
        'Core Web Vitals: LCP < 2.5s (loading), FID < 100ms (interactivity), CLS < 0.1 (visual stability)',
        'Widget integration: Use Chapter 27 media gallery for Instagram/TikTok-like experience, track all interactions',
        'Conversion tracking: Assign values (like=1, comment=5, save=10, pwa_install=50), send to analytics platforms',
        'PWA install prompt: Show after user engagement, non-intrusive, track install as high-value conversion',
      ],
    },
    {
      id: 286,
      title: 'Multi-Platform Analytics & Conversion Tracking',
      content: `
        <h2>Analytics Integration</h2>
        <p>Multi-platform tracking ensures reliable data collection and enables ad platform optimization algorithms.</p>

        <h3>Why Multi-Platform Tracking?</h3>
        <ul>
          <li><strong>Platform Optimization:</strong> Facebook/TikTok use pixel data to improve ad delivery</li>
          <li><strong>Backup/Redundancy:</strong> Ad blockers and cookie restrictions affect browser-side tracking</li>
          <li><strong>Different Attribution:</strong> Each platform has different attribution windows</li>
          <li><strong>Cross-Platform Insights:</strong> Compare performance across channels</li>
        </ul>

        <h3>Tracking Methods</h3>
        <table>
          <tr>
            <th>Method</th>
            <th>Reliability</th>
            <th>Affected By</th>
            <th>Use Case</th>
          </tr>
          <tr>
            <td>Browser Pixel</td>
            <td>Medium</td>
            <td>Ad blockers, cookie restrictions</td>
            <td>Standard tracking</td>
          </tr>
          <tr>
            <td>Server-Side API</td>
            <td>High</td>
            <td>None</td>
            <td>Backup, critical events</td>
          </tr>
        </table>

        <h3>Platforms</h3>
        <ul>
          <li><strong>Facebook Pixel:</strong> Browser JavaScript + Conversions API (server-side)</li>
          <li><strong>Google Analytics 4:</strong> Event-based analytics, cross-device tracking</li>
          <li><strong>TikTok Pixel:</strong> Browser JavaScript, standard and custom events</li>
        </ul>

        <h3>Event Mapping</h3>
        <p>Generic events mapped to platform-specific standard events:</p>
        <table>
          <tr>
            <th>Generic Event</th>
            <th>Facebook</th>
            <th>TikTok</th>
          </tr>
          <tr>
            <td>like</td>
            <td>Like</td>
            <td>Like</td>
          </tr>
          <tr>
            <td>comment</td>
            <td>Contact</td>
            <td>Contact</td>
          </tr>
          <tr>
            <td>save</td>
            <td>AddToWishlist</td>
            <td>AddToWishlist</td>
          </tr>
          <tr>
            <td>video_view</td>
            <td>ViewContent</td>
            <td>ViewContent</td>
          </tr>
          <tr>
            <td>pwa_installed</td>
            <td>Lead</td>
            <td>CompleteRegistration</td>
          </tr>
        </table>
      `,
      codeSnippets: [
        {
          id: 10,
          language: 'typescript',
          title: 'Multi-Platform Analytics Service',
          code: `// src/app/services/analytics/analytics.service.ts
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';

export interface ConversionEvent {
  eventName: string;
  mediaId?: string;
  value?: number;
  currency?: string;
  metadata?: Record<string, any>;
}

@Injectable({
  providedIn: 'root'
})
export class AnalyticsService {
  private readonly fbPixelId = 'YOUR_FB_PIXEL_ID';
  private readonly googleAnalyticsId = 'YOUR_GA_ID';
  private readonly tiktokPixelId = 'YOUR_TIKTOK_PIXEL_ID';
  private readonly conversionApiUrl = '/api/conversions';

  constructor(private readonly http: HttpClient) {
    this.initializeTracking();
  }

  private initializeTracking(): void {
    if (typeof window === 'undefined') return;

    this.loadFacebookPixel();
    this.loadGoogleAnalytics();
    this.loadTikTokPixel();
  }

  private loadFacebookPixel(): void {
    (function(f: any, b: any, e: any, v: any, n?: any, t?: any, s?: any) {
      if (f.fbq) return;
      n = f.fbq = function() {
        n.callMethod ? n.callMethod.apply(n, arguments) : n.queue.push(arguments);
      };
      if (!f._fbq) f._fbq = n;
      n.push = n;
      n.loaded = !0;
      n.version = '2.0';
      n.queue = [];
      t = b.createElement(e);
      t.async = !0;
      t.src = v;
      s = b.getElementsByTagName(e)[0];
      s.parentNode.insertBefore(t, s);
    })(window, document, 'script', 'https://connect.facebook.net/en_US/fbevents.js');

    (window as any).fbq('init', this.fbPixelId);
    (window as any).fbq('track', 'PageView');
  }

  private loadGoogleAnalytics(): void {
    const script = document.createElement('script');
    script.async = true;
    script.src = \`https://www.googletagmanager.com/gtag/js?id=\${this.googleAnalyticsId}\`;
    document.head.appendChild(script);

    (window as any).dataLayer = (window as any).dataLayer || [];
    function gtag(...args: any[]) {
      (window as any).dataLayer.push(arguments);
    }
    gtag('js', new Date());
    gtag('config', this.googleAnalyticsId);
    (window as any).gtag = gtag;
  }

  private loadTikTokPixel(): void {
    // TikTok pixel loading code (simplified)
    (window as any).ttq = (window as any).ttq || [];
    // ... TikTok pixel setup
  }

  trackPageView(pageName: string, properties?: Record<string, any>): void {
    // Facebook Pixel
    if ((window as any).fbq) {
      (window as any).fbq('track', 'PageView', properties);
    }

    // Google Analytics
    if ((window as any).gtag) {
      (window as any).gtag('event', 'page_view', {
        page_title: pageName,
        ...properties
      });
    }

    // TikTok Pixel
    if ((window as any).ttq) {
      (window as any).ttq.track('ViewContent', properties);
    }
  }

  trackAdClick(data: {
    source: string;
    medium: string;
    campaign: string;
    content?: string;
    adId?: string;
  }): void {
    this.trackEvent('ad_click', {
      source: data.source,
      medium: data.medium,
      campaign: data.campaign,
      content: data.content,
      ad_id: data.adId
    });
  }

  trackConversion(eventName: string, data: ConversionEvent): void {
    const properties = {
      event_name: eventName,
      value: data.value || 0,
      currency: data.currency || 'USD',
      ...data.metadata
    };

    // Facebook Pixel (browser-side)
    if ((window as any).fbq) {
      const fbEventName = this.mapToFacebookEvent(eventName);
      (window as any).fbq('track', fbEventName, properties);
    }

    // Google Analytics (browser-side)
    if ((window as any).gtag) {
      (window as any).gtag('event', eventName, properties);
    }

    // TikTok Pixel (browser-side)
    if ((window as any).ttq) {
      const ttEventName = this.mapToTikTokEvent(eventName);
      (window as any).ttq.track(ttEventName, properties);
    }

    // Server-side conversion tracking (backup)
    this.sendConversionToBackend(eventName, properties);
  }

  trackMediaInteraction(event: any): void {
    this.trackEvent('media_interaction', {
      event_type: event.eventType,
      media_id: event.mediaId,
      media_index: event.mediaIndex,
      ...event.metadata
    });
  }

  trackEvent(eventName: string, properties?: Record<string, any>): void {
    // Facebook
    if ((window as any).fbq) {
      (window as any).fbq('trackCustom', eventName, properties);
    }

    // Google Analytics
    if ((window as any).gtag) {
      (window as any).gtag('event', eventName, properties);
    }

    // TikTok
    if ((window as any).ttq) {
      (window as any).ttq.track(eventName, properties);
    }
  }

  private mapToFacebookEvent(eventName: string): string {
    const mapping: Record<string, string> = {
      'like': 'Like',
      'comment': 'Contact',
      'save': 'AddToWishlist',
      'video_view': 'ViewContent',
      'pwa_installed': 'Lead'
    };
    return mapping[eventName] || eventName;
  }

  private mapToTikTokEvent(eventName: string): string {
    const mapping: Record<string, string> = {
      'like': 'Like',
      'comment': 'Contact',
      'save': 'AddToWishlist',
      'video_view': 'ViewContent',
      'pwa_installed': 'CompleteRegistration'
    };
    return mapping[eventName] || eventName;
  }

  private sendConversionToBackend(eventName: string, properties: any): void {
    this.http.post(this.conversionApiUrl, {
      event_name: eventName,
      properties,
      timestamp: new Date().toISOString()
    }).subscribe();
  }
}`,
          copyable: true,
        },
      ],
      interviewTips: [
        'Multi-platform: Browser pixels (Facebook, Google, TikTok) + server-side API for redundancy and reliability',
        'Event mapping: Generic events mapped to platform-specific standard events (like→Like, pwa_installed→Lead/CompleteRegistration)',
        'Facebook Pixel: Standard events trigger optimization algorithms; server-side Conversions API bypasses ad blockers',
        'Google Analytics 4: Event-based model, cross-device tracking, custom events, conversion tracking',
        'Server-side tracking: More reliable (not blocked), includes server data, backup for browser-side, GDPR-compliant',
      ],
    },
    {
      id: 287,
      title: 'Campaign Optimization & A/B Testing',
      content: `
        <h2>Ad Campaign Optimization</h2>
        <p>Continuous optimization based on data is the key to improving ROAS (Return on Ad Spend).</p>

        <h3>Key Metrics</h3>
        <table>
          <tr>
            <th>Metric</th>
            <th>Formula</th>
            <th>Good Value</th>
          </tr>
          <tr>
            <td>CTR</td>
            <td>Clicks / Impressions</td>
            <td>Instagram: 0.5-1.5%, TikTok: 1-3%</td>
          </tr>
          <tr>
            <td>CPC</td>
            <td>Spend / Clicks</td>
            <td>$0.10 - $2.00 (varies by platform)</td>
          </tr>
          <tr>
            <td>Conversion Rate</td>
            <td>Conversions / Clicks</td>
            <td>2-5% (varies by industry)</td>
          </tr>
          <tr>
            <td>CPA</td>
            <td>Spend / Conversions</td>
            <td>< Customer LTV / 3</td>
          </tr>
          <tr>
            <td>ROAS</td>
            <td>Revenue / Spend</td>
            <td>E-comm: 4:1+, SaaS: 5:1+</td>
          </tr>
        </table>

        <h3>ROAS Optimization Strategies</h3>
        <ul>
          <li><strong>Increase Revenue:</strong> Upsell/cross-sell, increase prices, higher-value customers</li>
          <li><strong>Decrease Cost:</strong> Improve ad relevance, better targeting, optimize bidding, pause low performers</li>
          <li><strong>Improve Attribution:</strong> Multi-touch attribution, longer windows, view-through conversions</li>
        </ul>

        <h3>A/B Testing Framework</h3>
        <p>Test one variable at a time to isolate impact:</p>
        <ul>
          <li>Creative (image vs video, different hooks)</li>
          <li>Headline/copy variations</li>
          <li>CTA button text</li>
          <li>Targeting (different audiences)</li>
          <li>Placement (Feed vs Stories vs Reels)</li>
          <li>Bid strategy</li>
        </ul>

        <h3>Statistical Significance</h3>
        <p>Run tests until 95%+ confidence level:</p>
        <ul>
          <li>Calculate required sample size before starting</li>
          <li>Use chi-square test for conversion rate comparison</li>
          <li>Don't stop test early (results can change)</li>
          <li>Account for external factors (seasonality, events)</li>
        </ul>

        <h3>Budget Allocation</h3>
        <table>
          <tr>
            <th>Strategy</th>
            <th>Description</th>
            <th>Use Case</th>
          </tr>
          <tr>
            <td>Manual</td>
            <td>Set budget per ad set based on performance</td>
            <td>Full control, small scale</td>
          </tr>
          <tr>
            <td>CBO</td>
            <td>Campaign Budget Optimization (Meta)</td>
            <td>Auto-allocation to best performers</td>
          </tr>
          <tr>
            <td>ROAS-Based</td>
            <td>Allocate proportionally to ROAS</td>
            <td>Maximize profitability</td>
          </tr>
        </table>
      `,
      codeSnippets: [
        {
          id: 11,
          language: 'typescript',
          title: 'ROAS Calculation & Optimization',
          code: `// ROAS (Return on Ad Spend) calculation
interface RoasCalculation {
  revenue: number;
  adSpend: number;
  roas: number;
  targetRoas: number;
  isProfitable: boolean;
}

function calculateRoas(revenue: number, adSpend: number): RoasCalculation {
  const roas = revenue / adSpend;
  const targetRoas = 4.0; // Example target

  return {
    revenue,
    adSpend,
    roas,
    targetRoas,
    isProfitable: roas >= targetRoas
  };
}

// Example usage
const result = calculateRoas(10000, 2000);
console.log(\`ROAS: \${result.roas}:1\`); // 5:1
console.log(\`Profitable: \${result.isProfitable}\`); // true

// Budget allocation based on ROAS
interface BudgetAllocation {
  campaignId: string;
  totalBudget: number;
  adSets: Array<{
    adSetId: string;
    name: string;
    currentBudget: number;
    recommendedBudget: number;
    performance: {
      roas: number;
      cpa: number;
      conversionRate: number;
    };
  }>;
}

function optimizeBudgetAllocation(allocation: BudgetAllocation): BudgetAllocation {
  const adSets = allocation.adSets;

  // Calculate total weighted ROAS
  const totalWeightedRoas = adSets.reduce((sum, adSet) => sum + adSet.performance.roas, 0);

  // Allocate budget proportionally to ROAS
  const optimizedAdSets = adSets.map(adSet => {
    const budgetShare = adSet.performance.roas / totalWeightedRoas;
    const recommendedBudget = allocation.totalBudget * budgetShare;

    return {
      ...adSet,
      recommendedBudget
    };
  });

  return {
    ...allocation,
    adSets: optimizedAdSets
  };
}`,
          copyable: true,
        },
        {
          id: 12,
          language: 'typescript',
          title: 'A/B Testing Statistical Significance',
          code: `// A/B Test configuration
interface ABTest {
  id: string;
  name: string;
  hypothesis: string;
  variants: ABTestVariant[];
  status: 'running' | 'completed' | 'paused';
  winner?: string;
  confidence: number;
}

interface ABTestVariant {
  id: string;
  name: string;
  adId: string;
  metrics: {
    impressions: number;
    clicks: number;
    conversions: number;
    spend: number;
    ctr: number;
    conversionRate: number;
    cpa: number;
  };
}

// Calculate statistical significance (chi-square test)
function calculateSignificance(variantA: ABTestVariant, variantB: ABTestVariant): {
  winner: string | null;
  confidence: number;
  significant: boolean;
} {
  const totalA = variantA.metrics.clicks;
  const conversionsA = variantA.metrics.conversions;
  const totalB = variantB.metrics.clicks;
  const conversionsB = variantB.metrics.conversions;

  // Calculate chi-square statistic
  const pooledConversionRate = (conversionsA + conversionsB) / (totalA + totalB);
  const expectedA = totalA * pooledConversionRate;
  const expectedB = totalB * pooledConversionRate;

  const chiSquare =
    Math.pow(conversionsA - expectedA, 2) / expectedA +
    Math.pow(totalA - conversionsA - (totalA - expectedA), 2) / (totalA - expectedA) +
    Math.pow(conversionsB - expectedB, 2) / expectedB +
    Math.pow(totalB - conversionsB - (totalB - expectedB), 2) / (totalB - expectedB);

  // Convert to confidence (simplified)
  const confidence = chiSquare < 3.84 ? 90 : chiSquare < 6.63 ? 95 : 99;
  const significant = confidence >= 95;

  // Determine winner
  let winner: string | null = null;
  if (significant) {
    winner = variantA.metrics.conversionRate > variantB.metrics.conversionRate
      ? variantA.id
      : variantB.id;
  }

  return { winner, confidence, significant };
}

// Calculate required sample size
function calculateSampleSize(config: {
  baselineConversionRate: number;
  minimumDetectableEffect: number; // e.g., 0.10 = 10% improvement
  confidence: number; // e.g., 0.95 = 95%
  power: number; // typically 0.80 = 80%
}): number {
  const { baselineConversionRate, minimumDetectableEffect } = config;

  const zAlpha = 1.96; // 95% confidence
  const zBeta = 0.84;  // 80% power

  const p1 = baselineConversionRate;
  const p2 = baselineConversionRate * (1 + minimumDetectableEffect);
  const pBar = (p1 + p2) / 2;

  const sampleSize =
    (2 * Math.pow(zAlpha + zBeta, 2) * pBar * (1 - pBar)) /
    Math.pow(p2 - p1, 2);

  return Math.ceil(sampleSize);
}`,
          copyable: true,
        },
      ],
      interviewTips: [
        'ROAS formula: Revenue / Ad Spend; target varies by industry (e-comm 4:1, SaaS 5:1, lead gen 3:1)',
        'Optimization strategies: Increase revenue (upsell, higher-value customers), decrease cost (improve relevance, better targeting)',
        'A/B testing: Test one variable at a time, run until 95%+ confidence, calculate sample size beforehand, account for external factors',
        'Statistical significance: Use chi-square test for conversion rates, do not stop early, ensure adequate sample size',
        'Budget allocation: Manual (full control), CBO (auto-optimization), ROAS-based (proportional to performance)',
      ],
    },
    {
      id: 288,
      title: 'Complete Demo & Best Practices',
      content: `
        <h2>Production Checklist</h2>
        <p>Before deploying your social media advertising system to production, ensure all items are completed:</p>

        <h3>PWA Configuration</h3>
        <ul>
          <li>Configure service worker for production (workbox-build)</li>
          <li>Generate all PWA icon sizes (72px - 512px, maskable)</li>
          <li>Create app screenshots for manifest</li>
          <li>Set proper start_url with tracking</li>
          <li>Test installation on iOS Safari and Android Chrome</li>
          <li>Set up SSL certificate (required for PWA)</li>
        </ul>

        <h3>Ad Platform Setup</h3>
        <ul>
          <li>Create ad accounts on each platform</li>
          <li>Set up OAuth flows for authentication</li>
          <li>Store API credentials in environment variables</li>
          <li>Configure webhooks for real-time updates</li>
          <li>Set up billing and payment methods</li>
          <li>Request increased API rate limits if needed</li>
        </ul>

        <h3>Analytics Configuration</h3>
        <ul>
          <li>Create Facebook Pixel and Conversions API</li>
          <li>Set up Google Analytics 4 property</li>
          <li>Create TikTok Pixel</li>
          <li>Implement GDPR consent management</li>
          <li>Configure server-side tracking endpoint</li>
          <li>Test event firing in platform event managers</li>
        </ul>

        <h3>Performance Optimization</h3>
        <ul>
          <li>Optimize images (WebP, compression, responsive)</li>
          <li>Set up CDN for static assets</li>
          <li>Minify and bundle CSS/JS</li>
          <li>Implement lazy loading for below-fold content</li>
          <li>Measure and optimize Core Web Vitals</li>
          <li>Test on 3G network speeds</li>
        </ul>

        <h3>Security</h3>
        <ul>
          <li>Never expose API keys in client-side code</li>
          <li>Use environment variables for credentials</li>
          <li>Implement rate limiting on conversion API</li>
          <li>Validate all URL parameters</li>
          <li>Sanitize user inputs</li>
          <li>Set proper CORS headers</li>
        </ul>

        <h3>Monitoring & Debugging</h3>
        <ul>
          <li>Set up error tracking (Sentry, LogRocket)</li>
          <li>Monitor Core Web Vitals (real user monitoring)</li>
          <li>Track conversion pixel firing (platform event managers)</li>
          <li>Set up alerts for high CPA or low ROAS</li>
          <li>Log all API errors for debugging</li>
        </ul>

        <h2>Interview Best Practices Summary</h2>

        <h3>PWA</h3>
        <ul>
          <li>Service worker lifecycle: Register → Install → Activate → Fetch</li>
          <li>Workbox strategies: CacheFirst, NetworkFirst, StaleWhileRevalidate</li>
          <li>Installation: beforeinstallprompt event, standalone mode detection</li>
        </ul>

        <h3>Social Media Advertising</h3>
        <ul>
          <li>Campaign structure: Campaign → Ad Set/Group → Ad (3-tier)</li>
          <li>Metrics: CTR (engagement), CPC (efficiency), ROAS (profitability)</li>
          <li>Creative: Hook in 3 seconds, design for sound-off, match platform style</li>
        </ul>

        <h3>Deep Linking</h3>
        <ul>
          <li>UTM parameters: source, medium, campaign, content, term</li>
          <li>URL parsing: URLSearchParams API, store in sessionStorage</li>
          <li>Attribution: Last-click (simple), first-click (awareness), linear (equal)</li>
        </ul>

        <h3>Analytics</h3>
        <ul>
          <li>Multi-platform: Facebook Pixel, Google Analytics, TikTok Pixel</li>
          <li>Event mapping: Generic → platform-specific standard events</li>
          <li>Server-side: Backup for ad blockers, more reliable</li>
        </ul>

        <h3>Optimization</h3>
        <ul>
          <li>ROAS: Revenue / Spend (target 4:1+ for e-comm)</li>
          <li>A/B testing: One variable, 95%+ confidence, adequate sample size</li>
          <li>Budget: Allocate proportionally to ROAS, pause low performers</li>
        </ul>
      `,
      codeSnippets: [
        {
          id: 13,
          language: 'bash',
          title: 'Production Build Commands',
          code: `# Build PWA with service worker
npm run build --prod

# Generate service worker with Workbox
npx workbox generateSW workbox-config.js

# Build Ionic app for production
ionic build --prod

# Deploy to hosting (example: Firebase)
firebase deploy

# Test PWA in Chrome DevTools
# 1. Open Chrome DevTools
# 2. Application tab → Service Workers
# 3. Application tab → Manifest
# 4. Lighthouse tab → Progressive Web App audit`,
          copyable: true,
        },
        {
          id: 14,
          language: 'typescript',
          title: 'Environment Configuration',
          code: `// src/environments/environment.prod.ts
export const environment = {
  production: true,
  apiUrl: 'https://api.yourpwa.com',

  // Facebook/Instagram
  facebookAppId: process.env['FACEBOOK_APP_ID'],
  facebookAppSecret: process.env['FACEBOOK_APP_SECRET'],
  facebookPixelId: process.env['FACEBOOK_PIXEL_ID'],

  // TikTok
  tiktokAppId: process.env['TIKTOK_APP_ID'],
  tiktokAppSecret: process.env['TIKTOK_APP_SECRET'],
  tiktokPixelId: process.env['TIKTOK_PIXEL_ID'],

  // Google/YouTube
  googleClientId: process.env['GOOGLE_CLIENT_ID'],
  googleClientSecret: process.env['GOOGLE_CLIENT_SECRET'],
  googleAnalyticsId: process.env['GOOGLE_ANALYTICS_ID'],
  googleAdsDeveloperToken: process.env['GOOGLE_ADS_DEVELOPER_TOKEN'],

  // PWA
  pwaUrl: 'https://yourpwa.com',
  serviceWorkerUrl: '/service-worker.js',

  // Analytics
  enableAnalytics: true,
  enableServerSideTracking: true,

  // Feature flags
  enableInstagramAds: true,
  enableTikTokAds: true,
  enableFacebookAds: true,
  enableYouTubeAds: true
};`,
          copyable: true,
        },
      ],
      interviewTips: [
        'Production checklist: PWA icons/manifest, API credentials in env vars, SSL, GDPR consent, performance optimization',
        'Security: Never expose API keys client-side, use env variables, validate inputs, implement rate limiting',
        'Monitoring: Error tracking (Sentry), Core Web Vitals (RUM), conversion pixel verification, CPA/ROAS alerts',
        'Best practices: Test one variable, run until significant, allocate to winners, track everything, iterate continuously',
        'Common pitfalls: Stopping A/B tests early, not enough sample size, exposing credentials, slow landing pages, broken pixels',
      ],
    },
  ],
};
